### ISSUE TITLE
improve code readibility

### ISSUE THREAD

**Issue by girazoki** [witnet/elliptic-curve-solidity#24]
• Elliptic-curve-solidity\contracts\FastEcMul.sol:457-459 - Review indentation and
tabs.
• Elliptic-curve-solidity\contracts\FastEcMul.sol:39-41 - ab[1] = int256(- t[0]);
instead of ab[1] = int256(0 - t[0]); ab[3] = - t[1]; instead of ab[3] = 0 - t[1];
• Elliptic-curve-solidity\examples\Secp256k1.sol:0-31 - Despite being a pure function,
if a contract called it, the caller's privateKey could be published. A warning should be
displayed in the comment that reflects it to avoid problems for a user who implements it /
inherits it wrong.

**Comment by mariocao** [comment]
Closed in https://github.com/witnet/elliptic-curve-solidity/pull/27
