### ISSUE TITLE
Update solidity version requirement

### ISSUE THREAD

**Issue by Gooong** [witnet/elliptic-curve-solidity#33]
Hi,

Thanks for your work. This is very helpful. Currently solidity version goes up to 0.8.x. Could we update the solidity version requirement?

**Comment by aesedepece** [comment]
Hi @Gooong thanks for the heads up! Will get this done asap.

**Comment by AHaliq** [comment]
any updates on this?

**Comment by guidiaz** [comment]
Some package deps were deleted and the rest upgraded to latest versions. Solidity contracts and test support now any compiler compliant w/ `pragma solidity ^0.8.0^`, which was the goal of this issue. Unfortunately some test cases are raising arithmetic overflows within the `FastEcMul.decomposeScalar(..)` method. An assessment and eventual fix will be covered in #36.
